language: python
python:
  - "2.7"
# command to install dependencies
install:
  - sudo apt-get install python-dev libffi6 libffi-dev
  - pip install -r requirements.txt
# command to run tests
script: nosetests